### ISSUE TITLE
bug When I unzip the zip file and upload it to chrome

### ISSUE THREAD

**Issue by GLOMQuyet** [veraposeidon/SubtitleEasy#2]
**Describe the bug**
bug When I unzip the zip file and upload it to chrome

**To Reproduce**
Steps to reproduce the behavior, or file the issue is found in:

open File C:\Program Files\Subtitle Easy Error Manifest file is missing or unreadable
Or when I go through the dict folder and apply them to coursera, the subtitles don't work knowing that there are 2 folders macos and dict
 image: 
![image](https://github.com/veraposeidon/SubtitleEasy/assets/85043585/3a4686c7-f092-4e8e-8bea-7487317620ff)

**Comment by veraposeidon** [comment]
Based on your screenshot and description, it seems that you are using our plugin on Coursera videos. Currently, our plugin only supports Apple Developer and deeplearning.ai, and it hasn't fully supported Coursera yet. However, I'm glad to inform you that we have plans to add support for Coursera within the next two weeks.

In the meantime, I would suggest trying out a Chrome extension called [Dualsub](https://www.dualsub.xyz/), which already supports Coursera. You can give it a try to enhance your experience on Coursera. I hope this suggestion helps! If you have any other questions or need further assistance, please feel free to let me know.
